---
- hosts: localhost
  tasks:

  - name: Check Snapmirror State
    na_ontap_info:
      gather_subset: snapmirror_info
      hostname: "{{ item.dst_cluster }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
    register: sm_status
    until: sm_status.ontap_info.snapmirror_info[item.dst_svm+":"+item.dst_volume].relationship_status == "idle"
    delay: 10
    retries: 60
    loop: "{{ sm_list }}"
    loop_control:
      label: "{{ item.src_svm }}:{{ item.src_volume }} ---> {{ item.dst_svm }}:{{ item.dst_volume }}  --- Idle"

