---
- hosts: localhost
  gather_facts: no
  collections:
    - netapp.ontap

  tasks:
  - name: Delete Snapmirror Relationship
    na_ontap_snapmirror:
      hostname: "{{ item.dst_cluster }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
      source_hostname: "{{ item.src_cluster }}"
      state: absent
      relationship_info_only: true
      destination_path: "{{ item.dst_svm }}:{{ item.dst_volume }}"
      source_path: "{{ item.src_svm }}:{{ item.src_volume }}"
    loop: "{{ sm_list }}"
    loop_control:
      label: "{{ item.src_svm }}:{{ item.src_volume }} -x-> {{ item.dst_svm }}:{{ item.dst_volume }}  --- deleting"

