---
- hosts: localhost
  gather_facts: no
  collections:
    - netapp.ontap
  
  tasks:
  - debug:
      msg: "volume{{ my_idx|int +1 }} - {{ item.src_svm }}:{{ item.src_volume }} ---> {{ item.dst_svm }}:{{ item.dst_volume
}}"
    with_items: "{{ sm_list }}"
    loop_control:
      label: "{{ item.src_cluster }} ---> {{ item.dst_cluster }}"
      index_var: my_idx

