---
- hosts: localhost
  gather_facts: no
  collections:
    - netapp.ontap

  tasks:
  - name: Resync Snapmirror Reverse Relationship
    na_ontap_snapmirror:
      hostname: "{{ item.src_cluster }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
      state: present
      relationship_state: active
      source_path: "{{ item.dst_svm }}:{{ item.dst_volume }}"
      destination_path: "{{ item.src_svm }}:{{ item.src_volume }}"
    loop: "{{ sm_list }}"
    loop_control:
      label: "{{ item.src_svm }}:{{ item.src_volume }} <--- {{ item.dst_svm }}:{{ item.dst_volume }}  --- resyncing"

  - name: Check Snapmirror Reverse State
    na_ontap_info:
      gather_subset: snapmirror_info
      hostname: "{{ item.src_cluster }}"
      username: "{{ netapp_username }}"
      password: "{{ netapp_password }}"
      https: true
      validate_certs: false
    register: sm_status
    until: sm_status.ontap_info.snapmirror_info[item.src_svm+":"+item.src_volume].relationship_status == "idle"
    delay: 30
    retries: 240
    loop: "{{ sm_list }}"
    loop_control:
      label: "{{ item.src_svm }}:{{ item.src_volume }} <--- {{ item.dst_svm }}:{{ item.dst_volume }}  --- idle"


